DEFAULT_TEX_TEMPLATE: str = """
\\documentclass[preview]{{standalone}}
\\usepackage[spanish]{{babel}}
\\usepackage{{amsmath}}
\\usepackage{{amssymb}}
\\usepackage{{xcolor}}
\\usepackage{{mlmodern}}
\\usepackage{{hyperref}}
\\usepackage[outputdir=temp]{{minted}}
\\def\\markdownOptionOutputDir{{temp}}
\\ExplSyntaxOn
\\str_new:N
  \\g_luabridge_output_dirname_str
\\str_gset:NV
  \\g_luabridge_output_dirname_str
  \\markdownOptionOutputDir
\\ExplSyntaxOff
\\usepackage[smartEllipses,hashEnumerators,fencedCode]{{markdown}}
\\markdownSetup{{renderers={{
  link = {{\href{{#2}}{{#1}}}}
}}}}
\\usemintedstyle{{github-dark}}
\\begin{{document}}
\\color{{white}}
\\begin{{markdown}}[texMathDollars,texMathSingleBackslash,texMathDoubleBackslash]
{md}
\\end{{markdown}}
\\end{{document}}
""".strip()
